/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufmt.ic.posbd.chamados.gui;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author edy
 */
public class PrincipalJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalJFrame
     */
    public PrincipalJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JButton();
        ConteudoPrincipalJPanel = new javax.swing.JPanel();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        menuCadastrojMenu = new javax.swing.JMenu();
        menuCidadeMenu = new javax.swing.JMenuItem();
        menuEmpresajMenu = new javax.swing.JMenuItem();
        menuPessoajMenu = new javax.swing.JMenuItem();
        menuHardwarejMenu = new javax.swing.JMenuItem();
        menuChamadosjMenu = new javax.swing.JMenuItem();
        menuAjudajMenu = new javax.swing.JMenu();
        menuSobrejMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSair.setText("Sair");
        btnSair.setToolTipText("Sair do Aplicativo");
        btnSair.setName("btnSair"); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        ConteudoPrincipalJPanel.setLayout(new java.awt.BorderLayout());

        menuCadastrojMenu.setText("Cadastro");

        menuCidadeMenu.setText("Cidade");
        menuCidadeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCidadeMenuActionPerformed(evt);
            }
        });
        menuCadastrojMenu.add(menuCidadeMenu);

        menuEmpresajMenu.setText("Empresa");
        menuCadastrojMenu.add(menuEmpresajMenu);

        menuPessoajMenu.setText("Pessoa");
        menuCadastrojMenu.add(menuPessoajMenu);

        menuHardwarejMenu.setText("Hardware");
        menuCadastrojMenu.add(menuHardwarejMenu);

        menuChamadosjMenu.setText("Chamado");
        menuCadastrojMenu.add(menuChamadosjMenu);

        jMenuBarPrincipal.add(menuCadastrojMenu);

        menuAjudajMenu.setText("Ajuda");

        menuSobrejMenu.setText("Sobre");
        menuSobrejMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobrejMenuActionPerformed(evt);
            }
        });
        menuAjudajMenu.add(menuSobrejMenu);

        jMenuBarPrincipal.add(menuAjudajMenu);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConteudoPrincipalJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 459, Short.MAX_VALUE)
                .addComponent(btnSair))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(ConteudoPrincipalJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                .addComponent(btnSair))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setConteudo(JPanel tela) 
    { //* MANIA DE C#
        ConteudoPrincipalJPanel.removeAll();
        ConteudoPrincipalJPanel.add(tela);
        ConteudoPrincipalJPanel.setVisible(false);
        ConteudoPrincipalJPanel.setVisible(true);
    }


    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        //Sair
        int escolha = JOptionPane.showConfirmDialog(null, "Realmente deseas sair?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (escolha == 0) { //The ISSUE is here
            System.exit(0);
        } else {
            this.setFocusable(true);
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void menuSobrejMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobrejMenuActionPerformed
        // TODO add your handling code here:
       // SobreJPanel s = new SobreJPanel();
        this.setConteudo(new SobreJPanel());
    }//GEN-LAST:event_menuSobrejMenuActionPerformed

    private void menuCidadeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCidadeMenuActionPerformed
        // TODO add your handling code here:
        this.setConteudo(new CidadeJPanel());
    }//GEN-LAST:event_menuCidadeMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ConteudoPrincipalJPanel;
    private javax.swing.JButton btnSair;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu menuAjudajMenu;
    private javax.swing.JMenu menuCadastrojMenu;
    private javax.swing.JMenuItem menuChamadosjMenu;
    private javax.swing.JMenuItem menuCidadeMenu;
    private javax.swing.JMenuItem menuEmpresajMenu;
    private javax.swing.JMenuItem menuHardwarejMenu;
    private javax.swing.JMenuItem menuPessoajMenu;
    private javax.swing.JMenuItem menuSobrejMenu;
    // End of variables declaration//GEN-END:variables
}
